version: '3.8'
services:
  db:
    image: supabase/postgres:15.1.0.117
    container_name: supabase-db-lms
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - ${DB_PORT:-54328}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./supabase/volumes/db/data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d

  studio:
    image: supabase/studio:2026.03.23-sha-b7847b7
    container_name: supabase-studio-lms
    restart: always
    ports:
      - ${STUDIO_PORT:-54327}:3000
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_ORGANIZATION: "Default Organization"
      DEFAULT_PROJECT: "Default Project"
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL:-http://localhost:54329}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}

  kong:
    image: kong:2.8.1
    container_name: supabase-kong-lms
    restart: always
    ports:
      - ${KONG_PORT:-54329}:8000
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml

  auth:
    image: supabase/gotrue:v2.105.0
    container_name: supabase-auth-lms
    restart: always
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${SUPABASE_PUBLIC_URL:-http://localhost:54329}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?search_path=auth,public
      GOTRUE_SITE_URL: ${SITE_URL:-http://localhost:5173}
      GOTRUE_URI_ALLOW_LIST: ${SITE_URL:-http://localhost:5173}/*
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_DISABLE_SIGNUP: "false"

  rest:
    image: postgrest/postgrest:v11.2.0
    container_name: supabase-rest-lms
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"

  meta:
    image: supabase/postgres-meta:v0.96.1
    container_name: supabase-meta-lms
    restart: always
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
